print("My name is najwa")
print("I am 22 years old")
print("I live in Islamabad")
print("I am currently doing BSCS from Riphah International University Islamabad")
print("My hobby is to Exploring New Things")
